config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reports

  root 'reports#new'

end

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :user

end

app/models/url.rb
class Url < ActiveRecord::Base
	require 'nokogiri'
	require 'open-uri'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reports
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

	require 'open-uri'

	def index
		@reports = Report.where(user_id: current_user.id)
	end

	def show
		@reports = Report.where(user_id: current_user.id)
	end

	def new
		@reports = Report.where(user_id: current_user.id)
	end

	def create
		@report = Report.new(report_params)
		@report.user_id = current_user.id

		if @report.save
			flash[:notice] = "Successfully Added!"
			render action: "new"
		else
			flash[:alert] = "An Error Occured."
			render action: "new"
		end
	end

	def destroy
		@report = Report.find(params[:id])
		@report.destroy

		redirect_to reports_path
	end

private
	def report_params
		params.require(:report).permit(:url, :user_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nokogiri_test.rb
require 'rubygems'
require 'nokogiri'
require 'open-uri'

def generate(url)

doc = Nokogiri::HTML(open(url))
puts doc.at_css("p").text

end

app/helpers/prawn_test.rb
require "prawn"

words = "These are words"

Prawn::Document.generate("hello.pdf") do
	text words
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paper Moon - Document Generator</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Alegreya' rel='stylesheet' type='text/css'>
</head>
<body>

<table id="header">
  <tr>
    <td>
      <a href="/"><img id="logo" src="http://hd.wallpaperswide.com/thumbs/paper_moon-t2.jpg"></a>
    </td>
    <td>
    <h1>Paper Moon</h1>
    </td>
  </tr>
</table>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/reports/index.html.erb
<h2>Reports</h2>

<div id="report">
<% @reports.each do |report| %>
	<% doc = Nokogiri::HTML(open(report.url)) %>
	<strong><%= doc.at_css("h1").text %></strong><br><br>
	<%= doc.at_css("p:first-of-type").text %><br><br>
	<%= button_to 'Delete Report', report_path(report), method: :delete, data: { confirm: 'Are you sure?' } %><br><br>
<% end %>
</div>

<table id="footer">
	<tr>
		<td>	
			<%= current_user.email %>
		</td>
		<td>
			<%= link_to "Full Report as PDF", reports_path(@reports, :format => "pdf") %>
		</td>
		<td>
			<%= link_to "Add New Report", new_report_path %>
		</td>
		<td>
			<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
		</td>
	</tr>
</table>

app/views/reports/new.html.erb
<%= form_for :report, url: reports_path, :html => { :id => "enter_url" } do |f| %>
	<br><br>Enter URL: <br><br><%= f.text_field :url %><br><br>
	<%= f.submit "Add!" %>
<% end %>
<br>

<br><br><br>

<table id="footer">
	<tr>
		<td>	
			<%= current_user.email %>
		</td>
		<td>
		</td>
		<td>
			<%= link_to "My Reports", reports_path %>
		</td>
		<td>
			<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
		</td>
	</tr>
</table>